# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 17:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0006_partial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partial',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
